### ISSUE TITLE
作者你好, 为什么候选字永远只有2个. 无论怎么设置page_size参数?

### ISSUE THREAD

**Issue by wishWinds** [yanhuacuo/98wubi-tables#14]
无论使用单字模式还是词组模式候选字永远只有2个. 无论怎么设置page_size参数>2. 都无效. 但是设置为1有效. 说明喂给引擎的只有2个?

我使用的是Mac版本的.

**Comment by yanhuacuo** [comment]
# 您并没有准确描述问题

在输入法的编码匹配模式中，有「精确匹配」与「模糊匹配」。

- 精确匹配

在精确匹配模式下，只显示「输入法」对应的「候选」，并不显示未输入的后续编码。

> fghy 雨 寸  圷

> ff 寺 封

- 模糊匹配

你大约是想要「模糊匹配」，显示「后续存在的编码所对应的候选项」。

``````
 fixed:
  db_class: tabledb
  dictionary: wubi98_ci.extended
  disable_user_dict_for_patterns:
    - "^z.*$"
  enable_charset_filter: false
  enable_completion: false
  enable_encoder: true
  enable_sentence: false
  enable_user_dict: true
  encode_commit_history: false
  initial_quality: 1000
  max_phrase_length: 4

``````

把 `enable_completion: false` 改为 `enable_completion: true`

即可。

然而，并不建议这么做，`模糊匹配` 如孩童自行车后面辅助轮，一个成熟的形码使用者，应该使用`精确匹配`。
