### ISSUE TITLE
拼音反查候选框超出屏幕

### ISSUE THREAD

**Issue by xiaofami** [yanhuacuo/98wubi-tables#15]
运行环境为opensuse tumbleweed，对 rime.sh 进行修改后成功安装。（apt一行修改成  sudo zypper in -y fcitx5-rime librime-lua ）

安装后测试基本功能、字体、主题正常，但是使用拼音反查功能时，输入框左侧超出屏幕显示不全。

我尝试修改 `$HOME/.local/share/fcitx5/rime/default.custom.yaml` 文件，希望减少候选框长度，不过修改前后未发生变化：

```yaml
customization:
  distribution_code_name: Weasel
  distribution_version: 0.99.0
  generator: "Rime::SwitcherSettings"
  modified_time: "Mon Jan  6 23:28:26 2020"
  rime_version: 1.7.3
patch:
  schema_list:
    - {schema: wubi98_ci}
    - {schema: wubi98_dz}
    - {schema: py}
  menu/page_size: 5
```

![Screenshot_20230408_205654](https://user-images.githubusercontent.com/4654044/230723783-50f99793-337e-4f62-bc7d-afb9c2f37751.png)
![Screenshot_20230408_205732](https://user-images.githubusercontent.com/4654044/230723789-85d04174-1c87-4687-af1f-e17e2f91192b.png)

恳请作者不吝赐教！
